completed ticket 5 and refactored my article list to have article cards
779carney/frontend-news pull request #4
Opened 2023-05-31 11:27 UTC by 779carney

2023-05-31 13:06 UTC, HannahBurks requested changes
Nice work Ellie, we just need to add a loading state and message for if the data is loading. Once done, please send a PR tomorrow morning and you should be good to go!

2023-05-31 13:06 UTC, HannahBurks commented on src/components/SingleArticle.jsx
> + console.log(article_id);
Make sure to remove any stray console logs :)

2023-05-31 13:06 UTC, HannahBurks commented on src/components/SingleArticle.jsx
> + useEffect(()=>{
We also want to add a loading state, so if we are still awaiting the data a loading message can be displayed on the screen

2023-06-01 10:35 UTC, itsaliabdallah approved these changes
nice looks good,
merge away.

2023-06-01 11:07 UTC, merged